#:schema node_modules/wrangler/config-schema.json
name = "receipt-forwarder"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
binding = "R2"
bucket_name = "receipts"
